server:
  port: ${SANJY_CLIENT_WEB_SERVER_PORT}
  tomcat:
    max-swallow-size: -1
  shutdown: graceful

sanjy-client-web:
  logging:
    level: ${SANJY_CLIENT_WEB_LOGGING_LEVEL}
    file-path: ${SANJY_CLIENT_WEB_LOGGING_FILE_PATH:}
    appender: ${SANJY_CLIENT_WEB_LOGGING_APPENDER}
  application:
    name: ${spring.application.name}
    version: "@project.version@"
    description: "@project.description@"
    contact:
      name: ToDo-put-name #ToDo: Put real name
      url: https://google.com #ToDo: Put real site
      email: admin@admin.com #ToDo: Put real email
    documentation:
      url: https://google.com #ToDo: Put real site
      description: ToDo-put-documentation-description #ToDo: Put real doc
    channel: ${SANJY_CLIENT_WEB_EXTERNAL_HTTP_CLIENT_SANJY_SERVER_CHANNEL}
  external-http-clients:
    http-retry:
      max-attempt: ${SANJY_CLIENT_WEB_HTTP_RETRY_MAX_ATTEMPT}
      interval: ${SANJY_CLIENT_WEB_HTTP_RETRY_INTERVAL}
      backoff-multiplier: ${SANJY_CLIENT_WEB_HTTP_RETRY_BACKOFF_MULTIPLIER}
    sanjy-server:
      url: ${SANJY_CLIENT_WEB_EXTERNAL_HTTP_CLIENT_SANJY_SERVER_URL}
    github:
      url: ${SANJY_CLIENT_WEB_EXTERNAL_HTTP_CLIENT_GITHUB_URL}
  upload:
    max-file-size-in-mb: ${SANJY_CLIENT_WEB_SERVER_UPLOAD_MAX_FILE_SIZE_IN_MB}
  ai:
    openai:
      api-key: ${SANJY_CLIENT_WEB_AI_API_KEY_OPENAI:}
      model: ${SANJY_CLIENT_WEB_AI_MODEL:}
      max-tokens: ${SANJY_CLIENT_WEB_AI_MAX_TOKENS}
      temperature: ${SANJY_CLIENT_WEB_AI_MAX_TEMPERATURE}
      stop-sequences: ${SANJY_CLIENT_WEB_AI_MAX_STOP_SEQUENCES}
      top-p: ${SANJY_CLIENT_WEB_AI_MAX_STOP_TOP_P}
    anthropic:
      api-key: ${SANJY_CLIENT_WEB_AI_API_KEY_ANTHROPIC:}
      model: ${SANJY_CLIENT_WEB_AI_MODEL:}
      max-tokens: ${SANJY_CLIENT_WEB_AI_MAX_TOKENS}
      temperature: ${SANJY_CLIENT_WEB_AI_MAX_TEMPERATURE}
      stop-sequences: ${SANJY_CLIENT_WEB_AI_MAX_STOP_SEQUENCES}
      top-p: ${SANJY_CLIENT_WEB_AI_MAX_STOP_TOP_P}

spring:
  servlet:
    multipart:
      max-file-size: ${SANJY_CLIENT_WEB_SERVER_UPLOAD_MAX_FILE_SIZE_IN_MB}MB
      max-request-size: ${SANJY_CLIENT_WEB_SERVER_UPLOAD_MAX_REQUEST_SIZE_IN_MB}MB

  application:
    name: "@project.name@"

  main:
    banner-mode: off

  threads:
    virtual:
      enabled: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false

springdoc:
  api-docs:
    path: ${SANJY_CLIENT_WEB_OPEN_API_API_DOCS_PATH}
    resolve-schema-properties: true
    enabled: ${SANJY_CLIENT_WEB_OPEN_API_API_DOCS_ENABLE}
  override-with-generic-response: false
  swagger-ui:
    path: ${SANJY_CLIENT_WEB_OPEN_API_SWAGGER_UI_REDIRECT_PATH}
    enabled: ${SANJY_CLIENT_WEB_OPEN_API_SWAGGER_UI_ENABLE}

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              # ChatClient Logging
              advisor: ${SANJY_CLIENT_WEB_LOGGING_LEVEL}
